align variables on _HOME suffix

diff --git a/bin/iceburg-ci b/bin/iceburg-ci
--- a/bin/iceburg-ci
+++ b/bin/iceburg-ci
@@ -37,8 +37,10 @@ case "$1" in
     ;;
 esac
 
-[ -n "$PROJECT_ROOT" ] || die "PROJECT_ROOT cannot be empty"
-cd "$PROJECT_ROOT" || die "failed entering PROJECT_ROOT"
+# remain backwards compatible with PROJECT_ROOT if PROJECT_HOME is not set.
+export PROJECT_HOME=${PROJECT_HOME:-$PROJECT_ROOT}
+[ -n "$PROJECT_HOME" ] || die "PROJECT_HOME cannot be empty"
+cd "$PROJECT_HOME" || die "failed entering PROJECT_HOME"
 
 #
 # the CI platform should provide these variables. these are fallback defaults
@@ -62,13 +64,13 @@ export __VERSION="${__VERSION:-0.0.0}"
 #
 
 # backwards compatibility - TODO: remove
-export PIPELINE_ARTIFACTS_PATH="${PIPELINE_ARTIFACTS_PATH:-$PROJECT_ROOT/ci/artifacts/$PIPELINE_ID}"
+export PIPELINE_ARTIFACTS_PATH="${PIPELINE_ARTIFACTS_PATH:-$PROJECT_HOME/ci/artifacts/$PIPELINE_ID}"
 export PIPELINE_ARTIFACTS="$PIPELINE_ARTIFACTS_PATH"
 [ -d "$PIPELINE_ARTIFACTS_PATH" ] || mkdir -p "$PIPELINE_ARTIFACTS_PATH"
 export ICEBURG_CI_PATH="$PIPELINE_HOME"
 # env backwards compatibility
 
-export COMPOSE_PROJECT_NAME="${PROJECT_NAME:-$(basename "$PROJECT_ROOT")}-${PIPELINE_ID}"
+export COMPOSE_PROJECT_NAME="${PROJECT_NAME:-$(basename "$PROJECT_HOME")}-${PIPELINE_ID}"
 export COMPOSE_DOCKER_CLI_BUILD=1
 export DOCKER_BUILDKIT=1
 export DOCKER_CONFIG="${DOCKER_CONFIG:-$HOME/.docker}"
@@ -103,7 +105,7 @@ if [ "$GITLAB_CI" = true ]; then
     log "detected docker executor"
     BUILDS_VOLUME=$(docker inspect "$CONTAINER_ID" -f "{{ range .Mounts }}{{ if eq .Destination \"/builds\" }}{{ .Source }}{{end}}{{end}}" | cut -d "/" -f 6)
     if [ -n "$BUILDS_VOLUME" ]; then
-      export PROJECT_ROOT="$BUILDS_VOLUME:/builds"
+      export PROJECT_HOME="$BUILDS_VOLUME:/builds"
     fi
   fi
 elif $__DOCKER_DESKTOP; then
@@ -116,8 +118,8 @@ else
 fi
 
 run_flags+=(
-  --workdir "$PROJECT_ROOT"
-  -v "$PROJECT_ROOT:$PROJECT_ROOT"
+  --workdir "$PROJECT_HOME"
+  -v "$PROJECT_HOME:$PROJECT_HOME"
 )
 
 # passthrough the ssh auth socket if set
